// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnZmgA8lz-v4yud47YUMf4GSBUYMeHpRc',
    appId: '1:431913109575:web:5e1232c301c2220c4b8962',
    messagingSenderId: '431913109575',
    projectId: 'dofy-project',
    authDomain: 'dofy-project.firebaseapp.com',
    storageBucket: 'dofy-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE0e2DVFMCf66UQHPSh_bUY6W2VDov0F4',
    appId: '1:431913109575:android:520377d6d3fdef094b8962',
    messagingSenderId: '431913109575',
    projectId: 'dofy-project',
    storageBucket: 'dofy-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApozSi9IY6fi81c4EZVH70_qIhCXjTGdI',
    appId: '1:431913109575:ios:3e60a5f04fff44cc4b8962',
    messagingSenderId: '431913109575',
    projectId: 'dofy-project',
    storageBucket: 'dofy-project.appspot.com',
    iosBundleId: 'dj.dofy.dofy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApozSi9IY6fi81c4EZVH70_qIhCXjTGdI',
    appId: '1:431913109575:ios:a72a9b93a00d54174b8962',
    messagingSenderId: '431913109575',
    projectId: 'dofy-project',
    storageBucket: 'dofy-project.appspot.com',
    iosBundleId: 'dj.dofy.dofy.RunnerTests',
  );
}
